# Generated by Django 2.1.1 on 2018-10-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('Nim', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=255)),
                ('Alamat', models.CharField(max_length=255)),
                ('Telepon', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Divisi', models.CharField(choices=[('1', 'Manpro'), ('2', 'Marketing'), ('3', 'Teknikal')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=255)),
                ('Organisasi', models.CharField(max_length=255)),
                ('Telp', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Proyek',
            fields=[
                ('Id_proyek', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=255)),
                ('Jumlah_developer', models.IntegerField()),
                ('Deskripsi', models.TextField(blank=True, null=True)),
                ('Valid_time_start', models.DateField()),
                ('Valid_time_end', models.DateField()),
                ('Durasi', models.IntegerField()),
                ('Id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporalaps.Client')),
                ('Id_iit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='temporalaps.Anggota')),
            ],
        ),
    ]
