# Generated by Django 2.1.1 on 2018-10-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temporalaps', '0002_auto_20181004_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Telp',
            new_name='Telepon',
        ),
    ]
