# Generated by Django 2.1.1 on 2018-10-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temporalaps', '0004_auto_20181004_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.AddField(
            model_name='client',
            name='Id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
